# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JvCH24KYzhMPErNIPB2ZTFr6XO8zS-s2
"""

list=[1,2,3,"apple"]
print(list)



a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

a=0
c=[a]*4
print(c)

#list slicing
a=["a","b","c,","d","e","f",1,2,3]
print(a[1:3])
print(a[:1])
print(a[1:])
print(a[0:])

students=int(input("total number of students:"))
for i in range(students):
  age=int(input("enter age:"))
  hours=int(input("enter no.of hours studied:"))
  if age>=10 & hours>6:
    print("marks will be greater than 90 by 100")
    a=[age,hours]
    print(a)
  elif age>20 & hours>10:
    print("marks greater than 95% ")
  else:
    print("students get less marks")

a=[1,2,3]
b=a[:]
print(b)