# -*- coding: utf-8 -*-
"""python_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17qRFJFKR7n8XKcDVEl0qXpMieRl-a8hv
"""

print(dir(str))

#uppercase
a="hello world"
b=a.upper()
print(b)

#swapcase
a="hEllo World"
b=a.swapcase()
print(b)

#title case
a="hello world"
b=a.title()
print(b)

#replace
a="hello world"
b=a.replace("hello","hi")
print(b)



#count
a="hello world"
b=a.count("hello")
print(b)
c=a.count("l")
print(c)

#check the input is digit or not
a='123anc'
b=a.isdigit()
print(b)

#finding range without list
a=range(10)
print(a)

#with list
a=range(10)
b=list(a)
print(b)

#slicing
#stsrt,stop then steps
my_list=list(range(5,15,2))
print(my_list)

#function with return
def add(a,b):
  result=a+b
  return result
add(10,5)

#function with default value:
def greet(name,greetings="hello"):
  print(f"{greetings},{name}")
greet("Alice")

#function with *args
#demo:
def cal(*args):
  total=sum(args)
  return total
print("sum of 1,2,3,4,5",cal(1,2,3,4,5))
print("sum of 10,20,30 is",cal(10,20,30))

#creating a programe and adding 2 or more features to it
#predefined correct username and password
correct_username="admin"
correct_password="password123"
while True:
  user=input("enter user name:")
  password=input("enter password:")
  if user==correct_username and password==correct_password:
    print("login successful")
    break
  else:
    print("invalid username or password")

#built-in function example
def greet(name):
    return f"Hello, {name.capitalize()}!"

name_input = "john"
greeting = greet(name_input)
print(greeting)

def isstring(name):
  return isinstance(name,str)
name_input="john"
result=isstring(name_input)
print(result)

#user defined functions
def names(name):
  return name
names("John")

a=int(input("Enter a positive integer value: "))
s=0
for i in range(1,a+1):
  if i%2==0:
    print(i,end=",")
    s+=i
print("\n The sum of even number from 1 to",a,"is: ",s)